version: '3.8'
services:
  ui-service:
    container_name: ui-service
    image: jameskagunga254/ui-service:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend-network
watchtower:
  container_name: watchtower
  image: containrrr/watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: --interval 30 ui-service
  
networks:
  backend_network:
    driver: bridge