version: '3.8'
services:
  ui-service:
    container_name: ui-service
    image: jameskagunga254/ui-service:release-falconbet
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend-network
  
networks:
  backend_network:
    driver: bridge