services:
  ui-service:
    container_name: ui-service
    image: jameskagunga254/ui-service:release-bahatibet
    restart: always
    ports:
      - "3001:3001"
    networks:
      - ui_nw
  
networks:
  ui_nw:
    driver: bridge