services:
  ui-service:
    container_name: ui-service
    image: jameskagunga254/ui-service:release-bahatibet
    restart: always
    environment:
      - PORT=3003
    expose:
      - 3003
    ports:
      - 3001:3003
    networks:
      - identity_nw
networks:
  identity_nw:
    driver: bridge
