services:
  ui-service:
    container_name: ui-service
    image: jameskagunga254/ui-service:release-falconbet
    restart: always
    environment:
      - PORT=3001
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - ui_nw
networks:
  ui_nw:
    driver: bridge
