services:
  ui-service:
    container_name: ui-service
    image: jameskagunga254/ui-service:release-bahatibet
    restart: always
    ports:
      - "3001:3001"
    networks:
      - ui_nw
watchtower:
  container_name: watchtower
  image: containrrr/watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: --interval 30 ui_service_falconbet
  
networks:
  ui_nw:
    driver: bridge