name: UI CI/CD Pipeline
on:
  push:
    branches:
      - 'release-falconbet'
      - 'release-bahatibet'
jobs:
  deploy:
    name: Build and Push UI Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jameskagunga254
          password: dckr_pat_UoIBDViEYL_Pod_o2ALpTx9oaoY

      - name: Build and Push Docker Image for Client
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jameskagunga254/ui-service:${{ github.ref_name }}
